version: '3.7'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bumblebeeDB
            # MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql

    springboot:
        build: .
        container_name: springboot
        ports:
            - '8080:8080'
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bumblebeeDB
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        depends_on:
            - mysql

volumes:
    mysql-data:
